name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "enhancement"
  - title: "🛠 Improvements"
    label: "improvement"
  - title: "🐛 Bug Fixes"
    label: "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "refactoring"
  - title: "⛓️ Dependency update"
    label: "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "enhancement"
      - "improvement"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes
  $CHANGES

  ## Docker Images
  [ghcr.io/cosmo-workspace/cosmo-controller-manager:v$RESOLVED_VERSION](https://github.com/cosmo-workspace/cosmo/pkgs/container/cosmo-controller-manager)
  [ghcr.io/cosmo-workspace/cosmo-dashboard:v$RESOLVED_VERSION](https://github.com/cosmo-workspace/cosmo/pkgs/container/cosmo-dashboard)
  [ghcr.io/cosmo-workspace/cosmo-auth-proxy:v$RESOLVED_VERSION](https://github.com/cosmo-workspace/cosmo/pkgs/container/cosmo-auth-proxy)

  ## How to install
